---
title: "Publications"

bibliography: bibliography.bib

---

1. Lam M, Chen C, Li Z, Martin A, **Bryois J**, Ma X, Gaspar H, Ikeda M, Benyamin B, Brown B, Liu R, Zhou W, Huan L, Kamatani Y, Kim S, Kubo M, Kusumawardhani A, Liu C, Ma H, Periyasamy S, Takahashi A, Wang Q, Xu Z, Yu H, Zhu F, Genomics Consortium - Schizophrenia Working Group P, Schizophrenia Consortium I, REsearch on schizophrenineTwork-China and Netherland (GREAT-CN) G, Chen W, Faraone S, Glatt S, He L, Hyman S, Hwu H, Li T, McCarroll S, Neale B, Sklar P, Wildenauer D, Yu X, Zhang D, Mowry B, Lee J, Xu S, Sullivan P, Ripke S, O'Donovan M, Daly M, Qin S, Sham P, Iwata N, Hong K, Schwab S, Yue W, Tsuang M, Liu J, Ma X, Kahn R, Shi Y, Huang H [Comparative genetic architectures of schizophrenia in East Asian and European populations](https://www.biorxiv.org/content/early/2018/10/17/445874)
 BioRxiv, 2018

2. de Jong S, Diniz MJA, Saloma A, Gadelha A, Santoro ML, Ota VK, Noto C; **Major Depressive Disorder and Bipolar Disorder Working Groups of the Psychiatric Genomics Consortium**, Curtis C, Newhouse SJ, Patel H, Hall LS, O Reilly PF, Belangero SI, Bressan RA, Breen G. [Applying polygenic risk scoring for psychiatric disorders to a large family with bipolar disorder and major depressive disorder]() Communications Biology 2018 

3. Barbu MC, Zeng Y, Shen X, Cox SR, Clarke TK, Gibson J, Adams MJ3, Johnstone M, Haley CS, Lawrie SM, Deary IJ; Major Depressive Disorder Working Group of the Psychiatric Genomics Consortium; 23andMe Research Team, McIntosh AM, Whalley HC. [Association of Whole-Genome and NETRIN1 Signaling Pathway-Derived Polygenic Risk Scores for Major Depressive Disorder and White Matter Microstructure in the UK Biobank]() Biological Psychiatry: Cognitive Neuroscience and Neuroimaging, 2018

4. **Bryois J**#, Garrett ME#, Song L#, Safi A, Giusti-Rodriguez P, Johnson GD, Demur AB, Fullard JF, Roussos P, Sklar P, Akbarian S, Haroutunian V, Stockmeier CA, Wray GA, White KP, Liu C, Reddy TE, Ashley-Koch A, Sullivan PF\*, Crawford GE\* [Evaluation of chromatin accessibility in prefrontal cortex of individuals with schizophrenia]() Nature Communications, 2018 #Co-first

5. Yilmaz Z, Halvorsen M, **Bryois J**, Yu D, Disorders Working Group of the PGC E, Syndrome/OWorking Group of the PGC T, M. Thornton L, Zerwas S, Micali N, Moessner R, L. Burton C, Zai G, Erdman L, J. Kas M, D. Arnold P, K. Davis L, A. Knowles J, Breen G, M. Scharf J, Nestadt G, A. Mathews C, M. Bulik C, Mattheisen M, J. Crowley J [Examination of the Shared Genetic Basis of Anorexia Nervosa and Obsessive-Compulsive Disorder]() Molecular Psychiatry, 2018

6. Peyrot WJ, Van der Auwera S, Milaneschi Y, Dolan CV, Madden PAF, Sullivan PF, Strohmaier J, Ripke S, Rietschel M, Nivard MG, Mullins N, Montgomery GW, Henders AK, Heat AC, Fisher HL, Dunn EC, Byrne EM, Air TA, Wray NR, Mattheisen M, Trzaskowski M, Abdellaoui A, Adams MJ, Agerbo E, Air TM, Andlauer TFM, Bacanu S, Bækvad-Hansen M, Beekman ATF, Bigdeli TB, Binder EB, Blackwood DHR, **Bryois J**, Buttenschøn HN, Bybjerg-Grauholm J, Cai N, Castelao E, Hvarregaard Christensen J, Clarke T, Coleman JRI, Colodro-Conde L, Couvy-Duchesne B, Craddock N, Crawford GE, Davies G, Deary IJ, Degenhardt F, Derks EM, Direk N, Eley TC, Escott-Price V, Hassan Kiadeh F, Finucane HK, Forstner AJ, Frank J, Gaspar HA, Gill M, Goes FS, Gordon SD, Grove J, Hall LS, Søholm Hansen C, Hansen TF, Herms S, Hicki IB, Hoffmann P, Homuth G, Horn C, Hottenga J, Hougaard DM, Ising M, Jansen R, Jorgenson E, Knowles JA, Kohane IS, Kraft J, Kretzschmar WW, Krogh J, Kutalik Z, Li Y, Lind PA, MacIntyre DJ, MacKinnon DF, Maier RM, Maier W, Marchini J, Mbarek H, McGrath P, McGuffin P, Medland SE, Mehta D, Middeldorp CM, Mihailov E, Milani L, Mondimore FM, Mostafavi S, Nauck M, Ng B, Nyholt DR, O’Reilly PF, Oskarsson H, Owen MJ, Painter JN, Bøcker Pedersen C, Giørtz Pedersen M, Peterson RE, Pettersson E, Pistis G, Posthuma D, Quiroz JA, Qvist P, Rice JP, Riley BP, Rivera M, Saeed Mirza S, Schoevers R, Schulte EC, Shen L, Shi J, Shyn SI, Sigurdsson E, Sinnamon GCB, Smit JH, Smith DJ, Stefansson H, Steinberg S, Streit F, Tansey KE, Teismann H, Teumer A, Thompson W, Thomson PA, Thorgeirsson TE, Traylor M, Treutlein J, Trubetskoy V, Uitterlinden AG, Umbricht D, van Hemert AM, Viktorin A, Visscher PM, Wang Y, Webb BT, Marie Weinsheimer S, Wellmann J, Willemsen G, Witt SH, Wu Y, Xi HS, Yang J [Does Childhood Trauma Moderate Polygenic Risk for Depression? A Meta-analysis of 5765 Subjects From the Psychiatric Genomics Consortium]() Biological Psychiatry, 2018

7. Savage JE, Jansen PR, Stringer S, Watanabe K, **Bryois J**, de Leeuw CA, Nagel M, Awasthi S, Barr PB, Coleman JRI, Grasby KL, Hammerschlag AR, Kaminski J, Karlsson R, Krapohl E, Lam M, Nygaard M, Reynolds CA, Trampush JW, Young H, Zabaneh D, Hägg S, Hansell NK, Karlsson IK, Linnarsson S, Montgomery GW, Munoz-Manchado AB, Quinlan EB, Schumann G, Skene N, Webb BT, White T, Arking DE, Attix DK, Avramopoulos D, Bilder RM, Bitsios P, Burdick KE, Cannon TD, Chiba-Falek O, Christoforou A, Cirulli ET, Congdon E, Corvin A, Davies G, Deary IJ, DeRosse P, Dickinson D, Djurovic S, Donohoe G, Drabant Conley E, Eriksson JG, Espeseth T, Freimer NA, Giakoumaki S, Giegling I, Gill M, Glahn DC, Hariri AR, Hatzimanolis A, Keller MC, Knowles E, Konte B, Lahti J, Le Hellard S, Lencz T, Liewald DC, London E, Lundervold AJ, Malhotra AK, Melle I, Morris D, Need AC, Ollier W, Palotie A, Payton A, Pendleton N, Poldrack RA, Räikkönen K, Reinvang I, Roussos P, Rujescu D, Sabb FW, Scult MA, Smeland OB, Smyrnis N, Starr JM, Steen VM, Stefanis NC, Straub RE, Sundet K, Voineskos AN, Weinberger DR, Widen E, Yu J, Abecasis G, Andreassen OA, Breen G, Christiansen L, Debrabant B, Dick DM, Heinz A, Hjerling-Leffler J, Arfan Ikram M, Kendler KS, Martin NG, Medland SE, Pedersen NL, Plomin R, Polderman TJC, Ripke S, Sluis S, Sullivan PF, Tiemeier H, Vrieze SI, Wright MJ, Posthuma D [Genome-wide association meta-analysis in 269,867 individuals identifies new genetic and functional links to intelligence]() Nature Genetics, 2018

8. Nagel N, Jansen PR, Stringer S, Watanabe K, de Leeuw CA, **Bryois J**, Savage JE, Hammerschlag AR, Skene N, Munoz-Machado AB, 23andMe Research Team, Linnarsson S, Hjerling-Leffler J, White T, Tiemeier H, Polderman TJC, Sullivan PF, van der Sluis S, Posthuma D Meta-analysis of Genome-wide Association Studies for Neuroticism in 449,484 Individuals Identifies Novel Genetic Loci and Pathways Nature Genetics, 2018
Xia H, Jahr FM, Kim N, Xie L, Shabalin AA, **Bryois J**, Sweet DH, Kronfol MM, Palasuberniam P, McRae M, Riley BP, Sullivan PF, van den Oord EJ, McClay J Building a schizophrenia genetic network: Evidence that Transcription Factor 4 regulates schizophrenia risk genes Human Molecular Genetics, 2018
Skene NG#, **Bryois J**#, Bakken TE, Breen G, Crowley JJ, Gaspar HA, Giusti-Rodriguez P , Miller JA, Muñoz-Manchado A, O’Donovan MC, Owen MJ, Pardiñas AF, Ryge J, Walters JTR, Zeisel A, Linnarsson S, Lein ES, Sullivan PF\*, Hjerling-Leffler\* J [Genetic identification of brain cell types underlying schizophrenia]() Nature Genetics, 2018  #Co-first

9. **Major Depressive Disorder Working Group of the PGC**, Wray NR, Sullivan PF [Genome-wide association analyses identify 44 risk variants and refine the genetic architecture of major depression]() Nature Genetics, 2018

10. Coleman J, **Bryois J**, Gaspar HA, Jansen P, Savage J, Skene N, Plomin R, Munoz-Manchado A, Linnarsson S, Crawford G, Hjerling Leffler J, Sullivan PF, Posthuma D, Breen G [Biological annotation of genetic loci associated with intelligence in a meta-analysis of 87,740 individuals]() Molecular Psychiatry,2018

11. Kim Y, Giusti-Rodriguez P, Crowley JJ, **Bryois J**, Nonneman RJ, Ryan AK, Quackenbush CR, Iglesias-Ussel MD, Lee PH, Sun W, de Villena F PM, Sullivan PF [Comparative genomic evidence for the involvement of schizophrenia risk genes in antipsychotic effects]() Molecular Psychiatry, 2018

12. Nguyen HT, Dobbyn A, Charney A, **Bryois J**, Skene NG, Huckins LM, Wang W, Ruderfer DM, Xu X, Fromer M, Purcell SM, Verhage M, Smit AB, Hjerling-Leffler J, Buxbaum J, Pinto D, He X, Sullivan PF, Stahl EA [Prioritizing risk genes for neurodevelopmental disorders using pathway information]() BioRxiv, 2018

13. Jansen I, Savage J, Watanabe K, **Bryois J**, Williams D, Steinberg S, Sealock J, Karlsson I, Hagg S, Athanasiu L, Voyle N, Proitsi P, Witoelar A, Stringer S, Aarsland D, Almdahl I, Andersen F, Bergh S, Bettella F, Bjornsson S, Braekhus A, Brathen G, Leeuw C, Desikan R, Djurovic S, Dumitrescu L, Fladby T, Homan T, Jonsson P, Rongve A, Saltvedt I, Sando S, Selbak G, Skene N, Snaedal J, Stordal E, Ulstein I, Wang Y, White L, Hjerling-Leffler J, Sullivan P, Flier W, Dobson R, Davis L, Stefansson H, Stefansson K, Pedersen N, Ripke S, Andreassen O, Posthuma D Genetic meta-analysis identifies 10 novel loci and functional pathways for Alzheimer's disease risk Nature Genetics (in press), 2018

14. Jansen P, Watanabe K, Stringer S, Skene N, **Bryois J**, R. Hammerschlag A, A. de Leeuw C, Benjamins J, B. Muñoz-Manchado A, Nagel M, E. Savage J, Tiemeier H, White T, Research Team T, Y. Tung J, A. Hinds D, Vacic V, F. Sullivan P, Sluis S, J.C. Polderman T, B. Smit A, Hjerling-Leffler J, J.W. Van Someren E, Posthuma D Genome-wide Study of Insomnia (N=1,331,010) Identifies Novel Genetic Loci and Functional Pathways Nature Genetics (in press), 2018

15. Milaneschi Y, Lamers F, Peyrot WJ, Baune BT, Breen G, Dehghan A, Forstner AJ, Grabe HJ, Homuth G, Kan C, Lewis C, Mullins N, Nauck M, Pistis G, Preisig M, Rivera M, Rietschel M, Streit F, Strohmaier J, Teumer A, Van der Auwera S, Wray NR, Boomsma DI, Penninx BW,  CHARGE Inflammation Working Group and the **Major Depressive Disorder Working Group of the PGC**. [Genetic Association of Major Depression With Atypical Features and Obesity-Related Immunometabolic Dysregulations]() JAMA Psychiatry, 2017

15. Nguyen HT, **Bryois J**, Kim A, Dobbyn A, Huckins LM, Munoz-Manchado A, Ruderfer D, Genovese G, Fromer M, Xu X, Pinto D, Linnarsson S, Verhage M, Smit G, Hjerling-Leffler J, Buxbaum J, Hultman C, Sklar P, M. Purcell SM, He X, Sullivan PF, Stahl EA [Integrated Bayesian analysis of rare exonic variants to identify risk genes for schizophrenia and neurodevelopmental disorders]() Genome Medicine, 2017

16. **Bryois J**, Buil A, Ferreira P, Panoussis N, Brown A, Planchon A, Bielser D, Viñuela A, Small K, Spector T, Dermitzakis ET [Time-dependent genetic effects on gene expression implicate aging processes]() Genome Research, 2017 

17. SIB Swiss Institute of Bioinformatics Members [The SIB Swiss Institute of Bioinformatics’ resources: focus on curated databases]() Nucleic Acids Research, 2016 

18. Gutierrez-Arcelus M, Ongen H, Lappalainen T, Montgomery SB, Buil A, Yurovsky A, **Bryois J**, Padioleau I, Romano L, Planchon A, Falconnet E, Bielser D, Gagnebin M, Giger T, Borel C, Letourneau A, Makrythanasis P, Guipponi M, Gehrig C, Antonarakis SE, Dermitzakis ET [Tissue-specific effects of genetic and epigenetic variation on gene regulation and splicing]() PLoS Genetics, 2015

19. **Bryois J** [Long-range and temporal aspects of the genetics of gene expression]() PhD Thesis, 2015

20. **Bryois J**, Buil A, Evans DE, Kemp JP, Montgomery SB, Conrad DF, Ho KM, Ring S, Hurles M, Deloukas P, Davey Smith G, Dermitzakis ET [Cis and trans effects of human genomic variants on gene expression]() PLoS Genetics, 2014

21. Villanueva A, Willer JR, **Bryois J**, Dermitzakis ET, Katsanis N, Davis ED [Whole exome sequencing of a dominant retinitis pigmentosa family identifies a novel deletion in PRPF31]() Invest Ophthalmol Vis Sci.,2014

22. Kilpinen K, Waszak SM, Gschwind AR, Raghav SK, Witwicki RM, Orioli A, Migliavacca E, Wiederkehr M, Gutierrez-Arcelus M, Panousis NI, Yurovsky A, Lappalainen T, Romano-Palumbo L, Planchon A, Bielser D, **Bryois J**, Padioleau I, Udin G, Thurnheer S, Hacker D,  Core LJ, Lis JT, Hernandez N, Reymond A, Deplancke B, Dermitzakis ET [Coordinated effects of sequence variation on DNA binding, chromatin structure, and transcription]() Science, 2013

23. Gutierrez-Arcelus M, Lappalainen T, Montgomery SB, Buil A, Ongen H, Yurovsky A, **Bryois J**, Thomas Giger T, Romano L, Planchon A, Falconnet E, Bielser D, Gagnebin M, Padioleau I, Borel C, Letourneau A, Makrythanasis P, Guipponi M, Gehrig C, Antonarakis SE, Dermitzakis ET [Passive and active DNA methylation and the interplay with genetic variation in gene regulation]() Elife, 2013

24. Hens K, Feuz JD,, Isakova A, Iagovitina A, Massouras A, **Bryois J**, Callaerts P, Celniker SE, Deplancke B [Automated protein-DNA interaction screening of Drosophila regulatory elements]() Nature Methods, 2011

25. **Bryois J** Development of a gateway compatible system for speciﬁc DNA integration in mouse embryonic stem cells and evaluation of the effect of nucleosome positioning on gene expression Master thesis 2010